# Generated by Django 3.2.7 on 2021-09-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_tabel_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.staff'),
        ),
    ]
