# Generated by Django 3.2.7 on 2021-09-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_tabel_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.staff'),
        ),
    ]
